package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Continent generated by hbm2java
 */
public class Continent implements java.io.Serializable {

	private Long continentId;
	private String name;
	private Set<Country> countries = new HashSet<Country>(0);

	public Continent() {
	}

	public Continent(Long continentId, String name) {
		this.continentId = continentId;
		this.name = name;
	}

	public Continent(Long continentId, String name, Set<Country> countries) {
		this.continentId = continentId;
		this.name = name;
		this.countries = countries;
	}

	public Long getContinentId() {
		return this.continentId;
	}

	public void setContinentId(Long continentId) {
		this.continentId = continentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Country> getCountries() {
		return this.countries;
	}

	public void setCountries(Set<Country> countries) {
		this.countries = countries;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof Continent))
			return false;
		Continent castOther = (Continent) other;
		return new EqualsBuilder().append(name, castOther.getName()).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(131411285, 1830929643).append(name)
				.toHashCode();
	}

}
