package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * ContactTypes generated by hbm2java
 */
public class ContactTypes implements java.io.Serializable {

	private Long typeId;
	private String description;
	private Set<OperatorContact> operatorContacts = new HashSet<OperatorContact>(
			0);
	private Set<MainAgreementContact> mainAgreementContacts = new HashSet<MainAgreementContact>(
			0);

	public ContactTypes() {
	}

	public ContactTypes(Long typeId, String description) {
		this.typeId = typeId;
		this.description = description;
	}

	public ContactTypes(Long typeId, String description,
			Set<OperatorContact> operatorContacts,
			Set<MainAgreementContact> mainAgreementContacts) {
		this.typeId = typeId;
		this.description = description;
		this.operatorContacts = operatorContacts;
		this.mainAgreementContacts = mainAgreementContacts;
	}

	public Long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<OperatorContact> getOperatorContacts() {
		return this.operatorContacts;
	}

	public void setOperatorContacts(Set<OperatorContact> operatorContacts) {
		this.operatorContacts = operatorContacts;
	}

	public Set<MainAgreementContact> getMainAgreementContacts() {
		return this.mainAgreementContacts;
	}

	public void setMainAgreementContacts(
			Set<MainAgreementContact> mainAgreementContacts) {
		this.mainAgreementContacts = mainAgreementContacts;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof ContactTypes))
			return false;
		ContactTypes castOther = (ContactTypes) other;
		return new EqualsBuilder().append(description,
				castOther.getDescription()).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(1116239845, -768796653).append(description)
				.toHashCode();
	}

}
