package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * CountryRegion generated by hbm2java
 */
public class CountryRegion implements java.io.Serializable {

	private Long countryRegionId;
	private Country country;
	private String countryRegionName;
	private String additionalInfo;
	private Set<RoamingServiceTariff> roamingServiceTariffs = new HashSet<RoamingServiceTariff>(
			0);

	public CountryRegion() {
	}

	public CountryRegion(Long countryRegionId, Country country,
			String countryRegionName) {
		this.countryRegionId = countryRegionId;
		this.country = country;
		this.countryRegionName = countryRegionName;
	}

	public CountryRegion(Long countryRegionId, Country country,
			String countryRegionName, String additionalInfo) {
		this.countryRegionId = countryRegionId;
		this.country = country;
		this.countryRegionName = countryRegionName;
		this.additionalInfo = additionalInfo;
	}

	public Long getCountryRegionId() {
		return this.countryRegionId;
	}

	public void setCountryRegionId(Long countryRegionId) {
		this.countryRegionId = countryRegionId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getCountryRegionName() {
		return this.countryRegionName;
	}

	public void setCountryRegionName(String countryRegionName) {
		this.countryRegionName = countryRegionName;
	}

	public String getAdditionalInfo() {
		return this.additionalInfo;
	}

	public void setAdditionalInfo(String additionalInfo) {
		this.additionalInfo = additionalInfo;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof CountryRegion))
			return false;
		CountryRegion castOther = (CountryRegion) other;
		return new EqualsBuilder().append(countryRegionId,
				castOther.countryRegionId).isEquals();
	}

	public Set<RoamingServiceTariff> getRoamingServiceTariffs() {
		return roamingServiceTariffs;
	}

	public void setRoamingServiceTariffs(
			Set<RoamingServiceTariff> roamingServiceTariffs) {
		this.roamingServiceTariffs = roamingServiceTariffs;
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(1936966865, 934587843).append(
				countryRegionId).toHashCode();
	}

	// @Override
	// public boolean equals(final Object other) {
	// if (!(other instanceof CountryRegion))
	// return false;
	// CountryRegion castOther = (CountryRegion) other;
	// return new EqualsBuilder().append(country, castOther.getCountry())
	// .append(countryRegionName, castOther.getCountryRegionName())
	// .isEquals();
	// }
	//
	// @Override
	// public int hashCode() {
	// return new HashCodeBuilder(2032398965, -158256243).append(country)
	// .append(countryRegionName).toHashCode();
	// }

}
