package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * CountryIntDialingCode generated by hbm2java
 */
public class CountryIntDialingCode implements java.io.Serializable {

	private Long countryIntDialingCodeId;
	private Country country;
	private String dialingCode;
	private String carrier;

	public CountryIntDialingCode() {
	}

	public CountryIntDialingCode(Long countryIntDialingCodeId, Country country,
			String dialingCode, String carrier) {
		this.countryIntDialingCodeId = countryIntDialingCodeId;
		this.country = country;
		this.dialingCode = dialingCode;
		this.carrier = carrier;
	}

	public Long getCountryIntDialingCodeId() {
		return this.countryIntDialingCodeId;
	}

	public void setCountryIntDialingCodeId(Long countryIntDialingCodeId) {
		this.countryIntDialingCodeId = countryIntDialingCodeId;
	}

	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	public String getDialingCode() {
		return this.dialingCode;
	}

	public void setDialingCode(String dialingCode) {
		this.dialingCode = dialingCode;
	}

	public String getCarrier() {
		return this.carrier;
	}

	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof CountryIntDialingCode))
			return false;
		CountryIntDialingCode castOther = (CountryIntDialingCode) other;
		return new EqualsBuilder().append(country, castOther.getCountry())
				.append(dialingCode, castOther.getDialingCode()).append(
						carrier, castOther.getCarrier()).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(1554714027, 1926166699).append(country)
				.append(dialingCode).append(carrier).toHashCode();
	}

}
