package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * MainAgreement generated by hbm2java
 */
public class MainAgreement implements java.io.Serializable {

	private Long mainAgreementId;
	private String description;
	private Set<OperatorCountry> operatorCountries = new HashSet<OperatorCountry>(
			0);
	private Set<MainAgreementContact> mainAgreementContacts = new HashSet<MainAgreementContact>(
			0);
	private Set<MainAgreementConf> mainAgreementConfs = new HashSet<MainAgreementConf>(
			0);
	private Set<MainAgreementAddress> mainAgreementAddresses = new HashSet<MainAgreementAddress>(
			0);
	private Set<MainAgreementApproach> mainAgreementApproachs = new HashSet<MainAgreementApproach>(
			0);

	public MainAgreement() {
	}

	public MainAgreement(Long mainAgreementId, String description) {
		this.mainAgreementId = mainAgreementId;
		this.description = description;
	}

	public MainAgreement(Long mainAgreementId, String description,
			Set<OperatorCountry> operatorCountries,
			Set<MainAgreementContact> mainAgreementContacts,
			Set<MainAgreementConf> mainAgreementConfs,
			Set<MainAgreementAddress> mainAgreementAddresses,
			Set<MainAgreementApproach> mainAgreementApproachs) {
		this.mainAgreementId = mainAgreementId;
		this.description = description;
		this.operatorCountries = operatorCountries;
		this.mainAgreementContacts = mainAgreementContacts;
		this.mainAgreementConfs = mainAgreementConfs;
		this.mainAgreementAddresses = mainAgreementAddresses;
		this.mainAgreementApproachs = mainAgreementApproachs;
	}

	public Long getMainAgreementId() {
		return this.mainAgreementId;
	}

	public void setMainAgreementId(Long mainAgreementId) {
		this.mainAgreementId = mainAgreementId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<OperatorCountry> getOperatorCountries() {
		return operatorCountries;
	}

	public void setOperatorCountries(Set<OperatorCountry> operatorCountries) {
		this.operatorCountries = operatorCountries;
	}

	public Set<MainAgreementContact> getMainAgreementContacts() {
		return this.mainAgreementContacts;
	}

	public void setMainAgreementContacts(
			Set<MainAgreementContact> mainAgreementContacts) {
		this.mainAgreementContacts = mainAgreementContacts;
	}

	public Set<MainAgreementConf> getMainAgreementConfs() {
		return this.mainAgreementConfs;
	}

	public void setMainAgreementConfs(Set<MainAgreementConf> mainAgreementConfs) {
		this.mainAgreementConfs = mainAgreementConfs;
	}

	public Set<MainAgreementAddress> getMainAgreementAddresses() {
		return this.mainAgreementAddresses;
	}

	public void setMainAgreementAddresses(
			Set<MainAgreementAddress> mainAgreementAddresses) {
		this.mainAgreementAddresses = mainAgreementAddresses;
	}

	public Set<MainAgreementApproach> getMainAgreementApproachs() {
		return this.mainAgreementApproachs;
	}

	public void setMainAgreementApproachs(
			Set<MainAgreementApproach> mainAgreementApproachs) {
		this.mainAgreementApproachs = mainAgreementApproachs;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof MainAgreement))
			return false;
		MainAgreement castOther = (MainAgreement) other;
		return new EqualsBuilder().append(description, castOther.description)
				.isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(-1778429233, 316474065).append(description)
				.toHashCode();
	}

}
