package csv.roaming.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

/**
 * MainAgreementAddress generated by hbm2java
 */
public class MainAgreementAddress implements java.io.Serializable {

	private Long mainAgreementAddressId;
	private MainAgreement mainAgreement;
	private String address;
	private String city;
	private Boolean priority;

	public MainAgreementAddress() {
	}

	public MainAgreementAddress(Long mainAgreementAddressId,
			MainAgreement mainAgreement, String address) {
		this.mainAgreementAddressId = mainAgreementAddressId;
		this.mainAgreement = mainAgreement;
		this.address = address;
	}

	public MainAgreementAddress(Long mainAgreementAddressId,
			MainAgreement mainAgreement, String address, String city,
			Boolean priority) {
		this.mainAgreementAddressId = mainAgreementAddressId;
		this.mainAgreement = mainAgreement;
		this.address = address;
		this.city = city;
		this.priority = priority;
	}

	public Long getMainAgreementAddressId() {
		return this.mainAgreementAddressId;
	}

	public void setMainAgreementAddressId(Long mainAgreementAddressId) {
		this.mainAgreementAddressId = mainAgreementAddressId;
	}

	public MainAgreement getMainAgreement() {
		return this.mainAgreement;
	}

	public void setMainAgreement(MainAgreement mainAgreement) {
		this.mainAgreement = mainAgreement;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Boolean getPriority() {
		return this.priority;
	}

	public void setPriority(Boolean priority) {
		this.priority = priority;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof MainAgreementAddress))
			return false;
		MainAgreementAddress castOther = (MainAgreementAddress) other;
		return new EqualsBuilder().append(mainAgreement,
				castOther.mainAgreement).append(address, castOther.address)
				.append(city, castOther.city).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(-1817430565, -193850177).append(
				mainAgreement).append(address).append(city).toHashCode();
	}

}
