package csv.roaming.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

/**
 * MainAgreementConf generated by hbm2java
 */
public class MainAgreementConf implements java.io.Serializable {

	private Long mainAgreementConfId;
	private MainAgreement mainAgreement;
	private String confDetails;

	public MainAgreementConf() {
	}

	public MainAgreementConf(Long mainAgreementConfId,
			MainAgreement mainAgreement, String confDetails) {
		this.mainAgreementConfId = mainAgreementConfId;
		this.mainAgreement = mainAgreement;
		this.confDetails = confDetails;
	}

	public Long getMainAgreementConfId() {
		return this.mainAgreementConfId;
	}

	public void setMainAgreementConfId(Long mainAgreementConfId) {
		this.mainAgreementConfId = mainAgreementConfId;
	}

	public MainAgreement getMainAgreement() {
		return this.mainAgreement;
	}

	public void setMainAgreement(MainAgreement mainAgreement) {
		this.mainAgreement = mainAgreement;
	}

	public String getConfDetails() {
		return this.confDetails;
	}

	public void setConfDetails(String confDetails) {
		this.confDetails = confDetails;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof MainAgreementConf))
			return false;
		MainAgreementConf castOther = (MainAgreementConf) other;
		return new EqualsBuilder().append(mainAgreement,
				castOther.mainAgreement).append(confDetails,
				castOther.confDetails).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(-332309717, 629816425).append(mainAgreement)
				.append(confDetails).toHashCode();
	}

}
