package csv.roaming.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

/**
 * MainAgreementContact generated by hbm2java
 */
public class MainAgreementContact implements java.io.Serializable {

	private Long mainAgreementContactId;
	private ContactTypes contactTypes;
	private MainAgreement mainAgreement;
	private String contactName;
	private String contactSurname;
	private String phone;
	private String fax;
	private String gsm;
	private String email;
	private String contactTitle;

	public MainAgreementContact() {
	}

	public MainAgreementContact(Long mainAgreementContactId,
			MainAgreement mainAgreement, String contactName,
			String contactSurname) {
		this.mainAgreementContactId = mainAgreementContactId;
		this.mainAgreement = mainAgreement;
		this.contactName = contactName;
		this.contactSurname = contactSurname;
	}

	public MainAgreementContact(Long mainAgreementContactId,
			ContactTypes contactTypes, MainAgreement mainAgreement,
			String contactName, String contactSurname, String phone,
			String fax, String gsm, String email, String contactTitle) {
		this.mainAgreementContactId = mainAgreementContactId;
		this.contactTypes = contactTypes;
		this.mainAgreement = mainAgreement;
		this.contactName = contactName;
		this.contactSurname = contactSurname;
		this.phone = phone;
		this.fax = fax;
		this.gsm = gsm;
		this.email = email;
		this.contactTitle = contactTitle;
	}

	public Long getMainAgreementContactId() {
		return this.mainAgreementContactId;
	}

	public void setMainAgreementContactId(Long mainAgreementContactId) {
		this.mainAgreementContactId = mainAgreementContactId;
	}

	public ContactTypes getContactTypes() {
		return this.contactTypes;
	}

	public void setContactTypes(ContactTypes contactTypes) {
		this.contactTypes = contactTypes;
	}

	public MainAgreement getMainAgreement() {
		return this.mainAgreement;
	}

	public void setMainAgreement(MainAgreement mainAgreement) {
		this.mainAgreement = mainAgreement;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactSurname() {
		return this.contactSurname;
	}

	public void setContactSurname(String contactSurname) {
		this.contactSurname = contactSurname;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getGsm() {
		return this.gsm;
	}

	public void setGsm(String gsm) {
		this.gsm = gsm;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getContactTitle() {
		return this.contactTitle;
	}

	public void setContactTitle(String contactTitle) {
		this.contactTitle = contactTitle;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof MainAgreementContact))
			return false;
		MainAgreementContact castOther = (MainAgreementContact) other;
		return new EqualsBuilder().append(contactTypes, castOther.contactTypes)
				.append(mainAgreement, castOther.mainAgreement).append(
						contactName, castOther.contactName).append(
						contactSurname, castOther.contactSurname).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(-1253267197, -62691425).append(contactTypes)
				.append(mainAgreement).append(contactName).append(
						contactSurname).toHashCode();
	}

}
