package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * Mccmnc generated by hbm2java
 */
public class Mccmnc implements java.io.Serializable {

	private Long mccmncId;
	private String mccmnc;
	private Set<Operator> operators = new HashSet<Operator>(0);

	public Mccmnc() {
	}

	public Mccmnc(Long mccmncId, String mccmnc) {
		this.mccmncId = mccmncId;
		this.mccmnc = mccmnc;
	}

	public Mccmnc(Long mccmncId, String mccmnc, Set<Operator> operators) {
		this.mccmncId = mccmncId;
		this.mccmnc = mccmnc;
		this.operators = operators;
	}

	public Long getMccmncId() {
		return this.mccmncId;
	}

	public void setMccmncId(Long mccmncId) {
		this.mccmncId = mccmncId;
	}

	public String getMccmnc() {
		return this.mccmnc;
	}

	public void setMccmnc(String mccmnc) {
		this.mccmnc = mccmnc;
	}

	public Set<Operator> getOperators() {
		return this.operators;
	}

	public void setOperators(Set<Operator> operators) {
		this.operators = operators;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof Mccmnc))
			return false;
		Mccmnc castOther = (Mccmnc) other;
		return new EqualsBuilder().append(mccmnc, castOther.mccmnc).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(-874133407, -1984526727).append(mccmnc)
				.toHashCode();
	}

}
