package csv.roaming.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

/**
 * OperatorService generated by hbm2java
 */
public class OperatorService implements java.io.Serializable {

	private Long operatorServiceId;
	private RoamingService roamingService;
	private OperatorCountry operatorCountry;

	public OperatorService() {
	}

	public OperatorService(Long operatorServiceId,
			RoamingService roamingService, OperatorCountry operatorCountry) {
		this.operatorServiceId = operatorServiceId;
		this.roamingService = roamingService;
		this.operatorCountry = operatorCountry;
	}

	public Long getOperatorServiceId() {
		return this.operatorServiceId;
	}

	public void setOperatorServiceId(Long operatorServiceId) {
		this.operatorServiceId = operatorServiceId;
	}

	public RoamingService getRoamingService() {
		return this.roamingService;
	}

	public void setRoamingService(RoamingService roamingService) {
		this.roamingService = roamingService;
	}

	public OperatorCountry getOperatorCountry() {
		return operatorCountry;
	}

	public void setOperatorCountry(OperatorCountry operatorCountry) {
		this.operatorCountry = operatorCountry;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof OperatorService))
			return false;
		OperatorService castOther = (OperatorService) other;
		return new EqualsBuilder().append(roamingService,
				castOther.roamingService).append(operatorCountry,
				castOther.operatorCountry).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(1225654583, -2079062195).append(
				roamingService).append(operatorCountry).toHashCode();
	}

}
