package csv.roaming.domain;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

/**
 * RoamingServiceTariff generated by hbm2java
 */
public class RoamingServiceTariff implements java.io.Serializable {

	private Long roamingServiceTariffId;
	private RoamingService roamingService;
	private OperatorCountry operatorCountry;
	private CountryRegion countryRegion;
	private Double price;
	private String status;
	private String information;

	public RoamingServiceTariff() {
	}

	public RoamingServiceTariff(Long roamingServiceTariffId,
			RoamingService roamingService, OperatorCountry operatorCountry,
			CountryRegion countryRegion) {
		this.roamingServiceTariffId = roamingServiceTariffId;
		this.roamingService = roamingService;
		this.operatorCountry = operatorCountry;
		this.countryRegion = countryRegion;
	}

	public RoamingServiceTariff(Long roamingServiceTariffId,
			RoamingService roamingService, OperatorCountry operatorCountry,
			Double price, String status, CountryRegion countryRegion) {
		this.roamingServiceTariffId = roamingServiceTariffId;
		this.roamingService = roamingService;
		this.operatorCountry = operatorCountry;
		this.price = price;
		this.status = status;
		this.countryRegion = countryRegion;

	}

	public CountryRegion getCountryRegion() {
		return countryRegion;
	}

	public void setCountryRegion(CountryRegion countryRegion) {
		this.countryRegion = countryRegion;
	}

	public String getInformation() {
		return information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	public Long getRoamingServiceTariffId() {
		return this.roamingServiceTariffId;
	}

	public void setRoamingServiceTariffId(Long roamingServiceTariffId) {
		this.roamingServiceTariffId = roamingServiceTariffId;
	}

	public RoamingService getRoamingService() {
		return this.roamingService;
	}

	public void setRoamingService(RoamingService roamingService) {
		this.roamingService = roamingService;
	}

	public OperatorCountry getOperatorCountry() {
		return operatorCountry;
	}

	public void setOperatorCountry(OperatorCountry operatorCountry) {
		this.operatorCountry = operatorCountry;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof RoamingServiceTariff))
			return false;
		RoamingServiceTariff castOther = (RoamingServiceTariff) other;
		return new EqualsBuilder().append(roamingService,
				castOther.roamingService).append(operatorCountry,
				castOther.operatorCountry).append(status, castOther.status)
				.isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(-1084719943, -1055392059).append(
				roamingService).append(operatorCountry).append(status)
				.toHashCode();
	}

}
