package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * RoamingService generated by hbm2java
 */
public class RoamingService implements java.io.Serializable {

	private Long roamingServiceId;
	private String roamingServiceName;
	private Set<RoamingServiceTariff> roamingServiceTariffs = new HashSet<RoamingServiceTariff>(
			0);
	private Set<OperatorService> operatorServices = new HashSet<OperatorService>(
			0);

	public RoamingService() {
	}

	public RoamingService(Long roamingServiceId) {
		this.roamingServiceId = roamingServiceId;
	}

	public RoamingService(Long roamingServiceId, String roamingServiceName,
			Set<RoamingServiceTariff> roamingServiceTariffs,
			Set<OperatorService> operatorServices) {
		this.roamingServiceId = roamingServiceId;
		this.roamingServiceName = roamingServiceName;
		this.roamingServiceTariffs = roamingServiceTariffs;
		this.operatorServices = operatorServices;
	}

	public Long getRoamingServiceId() {
		return this.roamingServiceId;
	}

	public void setRoamingServiceId(Long roamingServiceId) {
		this.roamingServiceId = roamingServiceId;
	}

	public String getRoamingServiceName() {
		return this.roamingServiceName;
	}

	public void setRoamingServiceName(String roamingServiceName) {
		this.roamingServiceName = roamingServiceName;
	}

	public Set<RoamingServiceTariff> getRoamingServiceTariffs() {
		return this.roamingServiceTariffs;
	}

	public void setRoamingServiceTariffs(
			Set<RoamingServiceTariff> roamingServiceTariffs) {
		this.roamingServiceTariffs = roamingServiceTariffs;
	}

	public Set<OperatorService> getOperatorServices() {
		return this.operatorServices;
	}

	public void setOperatorServices(Set<OperatorService> operatorServices) {
		this.operatorServices = operatorServices;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof RoamingService))
			return false;
		RoamingService castOther = (RoamingService) other;
		return new EqualsBuilder().append(roamingServiceName,
				castOther.roamingServiceName).isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(-1733289055, 1565439513).append(
				roamingServiceName).toHashCode();
	}

}
