package csv.roaming.domain;

// Generated Oct 8, 2010 9:42:47 AM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * TariffCalculationParams generated by hbm2java
 */
public class TariffCalculationParams implements java.io.Serializable {

	private Long tariffCalcParamId;
	private Currency currency;
	private OperatorCountry operatorCountry;
	private Date validMonth;
	private Double currencyExchange;
	private Double exchange;
	private Short markup;
	private Short vat;
	private Double packetDataMultiplier;
	private Long gprsInitChargingInterval;
	private String gprsAdditionalDesc;
	private Long voiceInitChargingInterval;
	private Double callSetupCharge;
	private Double nationalVoiceMo;
	private Double backHomeVoiceMo;
	private Double rowVoiceMo;
	private Double sattelliteVoiceMo;
	private Double voiceMt;
	private Double smsMo;
	private Double gprsIotUnit;
	private Boolean active;
	private Date passiveDate;
	private MainAgreement mainAgreement;

	private Double exchangeRate;

	private Double womCallSetupCharge;
	private Double womNationalVoiceMo;
	private Double womBackHomeVoiceMo;
	private Double womRowVoiceMo;
	private Double womSattelliteVoiceMo;
	private Double womVoiceMt;
	private Double womSmsMo;
	private Double womGprsIotUnit;

	private Double wmCallSetupCharge;
	private Double wmNationalVoiceMo;
	private Double wmBackHomeVoiceMo;
	private Double wmRowVoiceMo;
	private Double wmSattelliteVoiceMo;
	private Double wmVoiceMt;
	private Double wmSmsMo;
	private Double wmGprsIotUnit;

	public TariffCalculationParams() {
	}

	public TariffCalculationParams(Long tariffCalcParamId,
			OperatorCountry operatorCountry, Date validMonth, Boolean active) {
		this.tariffCalcParamId = tariffCalcParamId;
		this.operatorCountry = operatorCountry;
		this.validMonth = validMonth;
		this.active = active;
	}

	public TariffCalculationParams(Long tariffCalcParamId, Currency currency,
			OperatorCountry operatorCountry, Date validMonth,
			Double currencyExchange, Double exchange, Short markup, Short vat,
			Double packetDataMultiplier, Long gprsInitChargingInterval,
			String gprsAdditionalDesc, Long voiceInitChargingInterval,
			Double callSetupCharge, Double nationalVoiceMo,
			Double backHomeVoiceMo, Double rowVoiceMo,
			Double sattelliteVoiceMo, Double voiceMt, Double smsMo,
			Double gprsIotUnit, Boolean active, Date passiveDate,
			MainAgreement mainAgreement, Double exchangeRate,
			Double womCallSetupCharge, Double womNationalVoiceMo,
			Double womBackHomeVoiceMo, Double womRowVoiceMo,
			Double womSattelliteVoiceMo, Double womVoiceMt, Double womSmsMo,
			Double womGprsIotUnit, Double wmCallSetupCharge,
			Double wmNationalVoiceMo, Double wmBackHomeVoiceMo,
			Double wmRowVoiceMo, Double wmSattelliteVoiceMo, Double wmVoiceMt,
			Double wmSmsMo, Double wmGprsIotUnit) {
		this.tariffCalcParamId = tariffCalcParamId;
		this.currency = currency;
		this.operatorCountry = operatorCountry;
		this.validMonth = validMonth;
		this.currencyExchange = currencyExchange;
		this.exchange = exchange;
		this.markup = markup;
		this.vat = vat;
		this.packetDataMultiplier = packetDataMultiplier;
		this.gprsInitChargingInterval = gprsInitChargingInterval;
		this.gprsAdditionalDesc = gprsAdditionalDesc;
		this.voiceInitChargingInterval = voiceInitChargingInterval;
		this.callSetupCharge = callSetupCharge;
		this.nationalVoiceMo = nationalVoiceMo;
		this.backHomeVoiceMo = backHomeVoiceMo;
		this.rowVoiceMo = rowVoiceMo;
		this.sattelliteVoiceMo = sattelliteVoiceMo;
		this.voiceMt = voiceMt;
		this.smsMo = smsMo;
		this.gprsIotUnit = gprsIotUnit;
		this.active = active;
		this.passiveDate = passiveDate;
		this.mainAgreement = mainAgreement;
		this.exchangeRate = exchangeRate;
		this.womCallSetupCharge = womCallSetupCharge;
		this.womNationalVoiceMo = womNationalVoiceMo;
		this.womBackHomeVoiceMo = womBackHomeVoiceMo;
		this.womRowVoiceMo = womRowVoiceMo;
		this.womSattelliteVoiceMo = womSattelliteVoiceMo;
		this.womVoiceMt = womVoiceMt;
		this.womSmsMo = womSmsMo;
		this.womGprsIotUnit = womGprsIotUnit;
		this.wmCallSetupCharge = wmCallSetupCharge;
		this.wmNationalVoiceMo = wmNationalVoiceMo;
		this.wmBackHomeVoiceMo = wmBackHomeVoiceMo;
		this.wmRowVoiceMo = wmRowVoiceMo;
		this.wmSattelliteVoiceMo = wmSattelliteVoiceMo;
		this.wmVoiceMt = wmVoiceMt;
		this.wmSmsMo = wmSmsMo;
		this.wmGprsIotUnit = wmGprsIotUnit;
	}

	public Double getExchangeRate() {
		return exchangeRate;
	}

	public void setExchangeRate(Double exchangeRate) {
		this.exchangeRate = exchangeRate;
	}

	public Double getWomCallSetupCharge() {
		return womCallSetupCharge;
	}

	public void setWomCallSetupCharge(Double womCallSetupCharge) {
		this.womCallSetupCharge = womCallSetupCharge;
	}

	public Double getWomNationalVoiceMo() {
		return womNationalVoiceMo;
	}

	public void setWomNationalVoiceMo(Double womNationalVoiceMo) {
		this.womNationalVoiceMo = womNationalVoiceMo;
	}

	public Double getWomBackHomeVoiceMo() {
		return womBackHomeVoiceMo;
	}

	public void setWomBackHomeVoiceMo(Double womBackHomeVoiceMo) {
		this.womBackHomeVoiceMo = womBackHomeVoiceMo;
	}

	public Double getWomRowVoiceMo() {
		return womRowVoiceMo;
	}

	public void setWomRowVoiceMo(Double womRowVoiceMo) {
		this.womRowVoiceMo = womRowVoiceMo;
	}

	public Double getWomSattelliteVoiceMo() {
		return womSattelliteVoiceMo;
	}

	public void setWomSattelliteVoiceMo(Double womSattelliteVoiceMo) {
		this.womSattelliteVoiceMo = womSattelliteVoiceMo;
	}

	public Double getWomVoiceMt() {
		return womVoiceMt;
	}

	public void setWomVoiceMt(Double womVoiceMt) {
		this.womVoiceMt = womVoiceMt;
	}

	public Double getWomSmsMo() {
		return womSmsMo;
	}

	public void setWomSmsMo(Double womSmsMo) {
		this.womSmsMo = womSmsMo;
	}

	public Double getWomGprsIotUnit() {
		return womGprsIotUnit;
	}

	public void setWomGprsIotUnit(Double womGprsIotUnit) {
		this.womGprsIotUnit = womGprsIotUnit;
	}

	public Double getWmCallSetupCharge() {
		return wmCallSetupCharge;
	}

	public void setWmCallSetupCharge(Double wmCallSetupCharge) {
		this.wmCallSetupCharge = wmCallSetupCharge;
	}

	public Double getWmNationalVoiceMo() {
		return wmNationalVoiceMo;
	}

	public void setWmNationalVoiceMo(Double wmNationalVoiceMo) {
		this.wmNationalVoiceMo = wmNationalVoiceMo;
	}

	public Double getWmBackHomeVoiceMo() {
		return wmBackHomeVoiceMo;
	}

	public void setWmBackHomeVoiceMo(Double wmBackHomeVoiceMo) {
		this.wmBackHomeVoiceMo = wmBackHomeVoiceMo;
	}

	public Double getWmRowVoiceMo() {
		return wmRowVoiceMo;
	}

	public void setWmRowVoiceMo(Double wmRowVoiceMo) {
		this.wmRowVoiceMo = wmRowVoiceMo;
	}

	public Double getWmSattelliteVoiceMo() {
		return wmSattelliteVoiceMo;
	}

	public void setWmSattelliteVoiceMo(Double wmSattelliteVoiceMo) {
		this.wmSattelliteVoiceMo = wmSattelliteVoiceMo;
	}

	public Double getWmVoiceMt() {
		return wmVoiceMt;
	}

	public void setWmVoiceMt(Double wmVoiceMt) {
		this.wmVoiceMt = wmVoiceMt;
	}

	public Double getWmSmsMo() {
		return wmSmsMo;
	}

	public void setWmSmsMo(Double wmSmsMo) {
		this.wmSmsMo = wmSmsMo;
	}

	public Double getWmGprsIotUnit() {
		return wmGprsIotUnit;
	}

	public void setWmGprsIotUnit(Double wmGprsIotUnit) {
		this.wmGprsIotUnit = wmGprsIotUnit;
	}

	public Long getTariffCalcParamId() {
		return this.tariffCalcParamId;
	}

	public void setTariffCalcParamId(Long tariffCalcParamId) {
		this.tariffCalcParamId = tariffCalcParamId;
	}

	public Currency getCurrency() {
		return this.currency;
	}

	public void setCurrency(Currency currency) {
		this.currency = currency;
	}

	public OperatorCountry getOperatorCountry() {
		return operatorCountry;
	}

	public void setOperatorCountry(OperatorCountry operatorCountry) {
		this.operatorCountry = operatorCountry;
	}

	public Date getValidMonth() {
		return this.validMonth;
	}

	public void setValidMonth(Date validMonth) {
		this.validMonth = validMonth;
	}

	public Double getCurrencyExchange() {
		return this.currencyExchange;
	}

	public void setCurrencyExchange(Double currencyExchange) {
		this.currencyExchange = currencyExchange;
	}

	public Double getExchange() {
		return this.exchange;
	}

	public void setExchange(Double exchange) {
		this.exchange = exchange;
	}

	public Short getMarkup() {
		return this.markup;
	}

	public void setMarkup(Short markup) {
		this.markup = markup;
	}

	public Short getVat() {
		return this.vat;
	}

	public void setVat(Short vat) {
		this.vat = vat;
	}

	public Double getPacketDataMultiplier() {
		return this.packetDataMultiplier;
	}

	public void setPacketDataMultiplier(Double packetDataMultiplier) {
		this.packetDataMultiplier = packetDataMultiplier;
	}

	public Long getGprsInitChargingInterval() {
		return this.gprsInitChargingInterval;
	}

	public void setGprsInitChargingInterval(Long gprsInitChargingInterval) {
		this.gprsInitChargingInterval = gprsInitChargingInterval;
	}

	public String getGprsAdditionalDesc() {
		return this.gprsAdditionalDesc;
	}

	public void setGprsAdditionalDesc(String gprsAdditionalDesc) {
		this.gprsAdditionalDesc = gprsAdditionalDesc;
	}

	public Long getVoiceInitChargingInterval() {
		return this.voiceInitChargingInterval;
	}

	public void setVoiceInitChargingInterval(Long voiceInitChargingInterval) {
		this.voiceInitChargingInterval = voiceInitChargingInterval;
	}

	public Double getCallSetupCharge() {
		return this.callSetupCharge;
	}

	public void setCallSetupCharge(Double callSetupCharge) {
		this.callSetupCharge = callSetupCharge;
	}

	public Double getNationalVoiceMo() {
		return this.nationalVoiceMo;
	}

	public void setNationalVoiceMo(Double nationalVoiceMo) {
		this.nationalVoiceMo = nationalVoiceMo;
	}

	public Double getBackHomeVoiceMo() {
		return this.backHomeVoiceMo;
	}

	public void setBackHomeVoiceMo(Double backHomeVoiceMo) {
		this.backHomeVoiceMo = backHomeVoiceMo;
	}

	public Double getRowVoiceMo() {
		return this.rowVoiceMo;
	}

	public void setRowVoiceMo(Double rowVoiceMo) {
		this.rowVoiceMo = rowVoiceMo;
	}

	public Double getSattelliteVoiceMo() {
		return this.sattelliteVoiceMo;
	}

	public void setSattelliteVoiceMo(Double sattelliteVoiceMo) {
		this.sattelliteVoiceMo = sattelliteVoiceMo;
	}

	public Double getVoiceMt() {
		return this.voiceMt;
	}

	public void setVoiceMt(Double voiceMt) {
		this.voiceMt = voiceMt;
	}

	public Double getSmsMo() {
		return this.smsMo;
	}

	public void setSmsMo(Double smsMo) {
		this.smsMo = smsMo;
	}

	public Double getGprsIotUnit() {
		return this.gprsIotUnit;
	}

	public void setGprsIotUnit(Double gprsIotUnit) {
		this.gprsIotUnit = gprsIotUnit;
	}

	public Boolean getActive() {
		return active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Date getPassiveDate() {
		return passiveDate;
	}

	public void setPassiveDate(Date passiveDate) {
		this.passiveDate = passiveDate;
	}

	public MainAgreement getMainAgreement() {
		return mainAgreement;
	}

	public void setMainAgreement(MainAgreement mainAgreement) {
		this.mainAgreement = mainAgreement;
	}

	@Override
	public boolean equals(final Object other) {
		if (!(other instanceof TariffCalculationParams))
			return false;
		TariffCalculationParams castOther = (TariffCalculationParams) other;
		return new EqualsBuilder().append(operatorCountry,
				castOther.operatorCountry).append(validMonth,
				castOther.validMonth).append(active, castOther.active)
				.isEquals();
	}

	@Override
	public int hashCode() {
		return new HashCodeBuilder(818220753, 1749906639).append(
				operatorCountry).append(validMonth).append(active).toHashCode();
	}

}
